#!/bin/bash
revert() {
  rm /tmp/locking_screen.png
  xset dpms 0 0 0
}
trap revert HUP INT TERM
xset +dpms dpms 0 0 5
scrot /tmp/locking_screen.png
#convert -scale 10% -resize 1000% /tmp/locking_screen.png /tmp/screen_blur.png
convert -spread 2 -swirl 216  /tmp/locking_screen.png /tmp/locking_screen.png
#convert -composite /tmp/screen_blur.png ~/Pictures/Evil_Rick_Sprite.png -gravity South -geometry -20x1200 /tmp/screen.png
i3lock -i /tmp/locking_screen.png
revert
